#!/bin/bash
#
# This script deletes all S3 buckets from one region
#
# This is - needless to say - a very dangerous operation. BE CAREFUL!
# This is meant to speed up deletion of buckets when clearing out an Account during
# CloudFormation Template testing.
#


#  1. Initalize Environment

scriptsdir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

step=0
speed_max=400
run_default=10
pause_default=2
next_default=5
create_default=15
create_attempts=40

interactive=0
speed=100
buckets=all
region=${AWS_DEFAULT_REGION:-us-west-2}
account=${AWS_ACCOUNT_ALIAS:-dxcapp}
user=${AWS_USER_NAME:-administrator}

standard_buckets="templates functions scripts configurations products backups"
log_buckets="archive-logs loadbalancer-logs config cloudtrail"
build_buckets="applications examples demos users"


#  2. Define functions

usage () {
    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-d]"
    echo "                  [-B bucket]"
    echo "                  [-r region] [-a account] [-u user]"
    echo "  -i              interactive"
    echo "  -s              slower: increase pauses by 25%"
    echo "  -f              faster: reduce pauses by 25%"
    echo "  -v              verbose"
    echo "  -B bucket       Bucket [or 'all'] (default: $buckets)"
    echo "  -r region       Region (default: $region)"
    echo "  -a account      Account (default: $account)"
    echo "  -u user         User (default: $user)"
}

run() {
    if [ -z $1 ] || (($1 % 25 != 0)); then
        ((seconds=run_default * speed / 100))
    else
        ((seconds=run_default * $1 * speed / 10000))
    fi
    if [ $interactive = 1 ]; then
        echo
        echo -n "Run? [Y/n/q]"
        read choice
        case "$choice" in
            "" | "y" | "Y" | "yes" | "Yes") choice=y ;;
            "n" | "N" | "no" | "No") choice=n ;;
             *) echo "cancelled"
                exit 2;;
        esac
    else
        echo
        echo -n -e "Waiting $(printf '%2d' $seconds) seconds..."
        while ((seconds > 0)); do
            if ((seconds < 10 || seconds % 10 == 0)); then
                echo -n -e "\rWaiting $(printf '%2d' $seconds) seconds..."
            fi
            sleep 1
            ((seconds--))
        done
        echo " Done"
        choice=y
    fi
}

pause() {
    if [ -z $1 ] || (($1 % 25 != 0)); then
        ((seconds=pause_default * speed / 100))
    else
        ((seconds=pause_default * $1 * speed / 10000))
    fi
    if [ $interactive = 1 ]; then
        echo "#"
        read pause
        echo -en "\033[1A\033[2K"    # undo newline from read
    else
        echo "#"
        sleep $seconds
    fi
}

next() {
    if [ -z $1 ] || (($1 % 25 != 0)); then
        ((seconds=next_default * speed / 100))
    else
        ((seconds=next_default * $1 * speed / 10000))
    fi
    if [ $interactive = 1 ]; then
        echo
        echo -n "Next? [Y/q]"
        read choice
        case "$choice" in
            "" | "y" | "Y" | "yes" | "Yes") choice=y ;;
             *) echo "cancelled"
                exit 2;;
        esac
    else
        echo
        echo -n -e "Waiting $(printf '%2d' $seconds) seconds..."
        while ((seconds > 0)); do
            if ((seconds < 10 || seconds % 10 == 0)); then
                echo -n -e "\rWaiting $(printf '%2d' $seconds) seconds..."
            fi
            sleep 1
            ((seconds--))
        done
        echo " Done"
        choice=y
    fi
}


#  3. Parse command line options

while getopts isfvB:r:a:u:? arg; do
    case $arg in
    i)  interactive=1;;
    s)  ((speed < speed_max)) && ((speed=speed+25));;
    f)  ((speed > 0)) && ((speed=speed-25));;
    v)  quiet="";;
    B)  buckets="$OPTARG";;
    r)  region="$OPTARG";;
    a)  account="$OPTARG";;
    u)  user="$OPTARG";;
    ?)  usage
        exit 1;;
    esac
done

shift $(($OPTIND - 1))


#  4. Validate environment

if [ -z $buckets ]; then
    echo "-B bucket missing!"
    echo "Could not automatically determine bucket, and it was not specified as a parameter"
    exit 10
else
    case $buckets in
      all)
        buckets="$standard_buckets $log_buckets $build_buckets";;
      standard)
        buckets=$standard_buckets;;
      log)
        buckets=$log_buckets;;
      build)
        buckets=$build_buckets;;
      templates)
        ;;
      functions)
        ;;
      scripts)
        ;;
      configurations)
        ;;
      products)
        ;;
      backups)
        ;;
      archive-logs)
        ;;
      loadbalancer-logs)
        ;;
      config)
        ;;
      cloudtrail)
        ;;
      applications)
        ;;
      examples)
        ;;
      demos)
        ;;
      users)
        ;;
      *)
        echo "-B $buckets invalid! Must be all, standard, log, build, templates, functions, scripts, configurations, products, backups, archive-logs, loadbalancer, config, cloudtrail, applications, examples, demos or users"
        exit 11;;
    esac
fi

if [ -z "$region" ]; then
    echo "-r region missing!"
    echo "Could not automatically determine region, and it was not specified as a parameter"
    exit 50
else
    case $region in
      us-east-1)
        s3_domain=s3.amazonaws.com;;
      us-east-2|us-west-1|us-west-2|ca-central-1|eu-west-1|eu-central-1|eu-west-2|eu-west-3|eu-north-1|ap-east-1|ap-southeast-1|ap-southeast-2|ap-northeast-2|ap-northeast-1|ap-south-1|me-south-1|sa-east-1)
        s3_domain=s3-$region.amazonaws.com;;
      *)
        echo "-r $region invalid: Please specify a valid region"
        exit 51;;
    esac
fi

if [ -z $account ]; then
    echo "-a account missing!"
    echo "Could not automatically determine account, and it was not specified as a parameter"
    exit 52
fi

if [ -z $user ]; then
    echo "-u user missing!"
    echo "Could not automatically determine user, and it was not specified as a parameter"
    exit 54
fi

profile=$account-$user

if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
    echo "Could not find ($account) Account ($user) User AWSCLI profile!"
    echo "Expected to find: [profile $profile] in ~/.aws/config"
    exit 58
fi

# Prevent certain environment variables from breaking commands
unset AWS_DEFAULT_PROFILE
unset AWS_CREDENTIAL_FILE
unset EC2_PRIVATE_KEY
unset EC2_CERT


#  5. Run

start=$(date +%s)

for bucket in $buckets; do
((++step))
read -r -d '' statement << EOS
object_versions=\$(aws s3api list-object-versions --bucket $bucket-$account-$region \\
                                                 --query  'Versions[].[Key,VersionId]' \\
                                                 --profile $profile --region $region --output text | tr '\t' ':');
EOS
run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
eval_statement="${statement//\\$'\n'}"

read -r -d '' statement2 << EOS
for ov in \$object_versions; do \\
  key=\${ov%:*};
  version=\${ov#*:};
  echo "Deleting: key=[\$key], version=[\$version]"
  aws s3api delete-object --bucket $bucket-$account-$region \\
                          --key \$key \\
                          --version-id \$version \\
                          --profile $profile --region $region --output text
done
EOS
run_statement2=$(echo "$statement2" | sed -e '1s/^/# /;2,$ s/^/> /')
eval_statement2="${statement2//\\$'\n'}"

clear
echo
echo "============================================================"
echo
echo "$(printf '%2d' $step). Empty $bucket-$account-$region Bucket"
echo
echo "============================================================"
echo
echo "Commands:"
echo
echo "$statement"
echo
echo "$statement2"

run 50

if [ $choice = y ]; then
    echo
    echo "$run_statement"
    eval "$eval_statement"

    if [ ! "$object_versions" = "None" ]; then
        echo
        echo "$run_statement2"
        eval "$eval_statement2"
    fi

    next
fi


((++step))
read -r -d '' statement << EOS
aws s3api delete-bucket --bucket $bucket-$account-$region \\
                        --profile $profile --region $region --output text;
EOS
run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
eval_statement="${statement//\\$'\n'}"

clear
echo
echo "============================================================"
echo
echo "$(printf '%2d' $step). Delete Empty $bucket-$account-$region Bucket"
echo
echo "============================================================"
echo
echo "Commands:"
echo
echo "$statement"

run 50

if [ $choice = y ]; then
    echo
    echo "$run_statement"
    eval "$eval_statement"

    next
fi
done

end=$(date +%s)

echo
case $(uname) in
  Darwin)
    echo "(time: $(date -u -r $((end-start)) +"%T"))";;
  *)
    echo "(time: $(date -u -d @$((end-start)) +"%T"))";;
esac
